web/cbay/basket/urls.py
from django.urls import path
from . import views


app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

web/cbay/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("review/", include("review.urls", namespace="review")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/cbay/store/urls.py
from django.urls import path

from . import views

# matches the /core/urls namespace url pattern list
app_name = "store"

urlpatterns = [
    path("", views.product_all, name="product_all"),
    path("<slug:item_slug>", views.product_detail, name="product_detail"),
    path("search/<slug:category_slug>/", views.category_list, name="category_list"),
]

web/cbay/store/models.py
from django.contrib.auth.models import User
from account.models import UserBase
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)  # category name
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:

        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):

    category = models.ForeignKey(
        Category, related_name="product", on_delete=models.CASCADE
    )
    # **User** is a standard django table
    created_by = models.ForeignKey(
        UserBase, on_delete=models.CASCADE, related_name="product_creator"
    )
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, default="")
    uses = models.TextField(blank=True)
    dosage = models.TextField(blank=True)
    side_effects = models.TextField(blank=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    # WE ARE NOT STORING IMAGE IN DB ---> WE STORE LINK TO IT
    image = models.ImageField(upload_to="images/", default="images/default.png")
    slug = models.SlugField(max_length=255, unique=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title

web/cbay/store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product
from review.models import ProductReview
from django.db.models import Avg
from django.core.paginator import Paginator

def product_all(request):
    products = Product.products.all()
    return render(request, "store/home.html", {"products": products})


def product_detail(request, item_slug):
    """Getting single product details"""
    product = get_object_or_404(Product, slug=item_slug, in_stock=True, is_active=True)
    reviews = ProductReview.objects.filter(product=product).order_by('-created')
    avg_rate = list(reviews.aggregate(Avg("rate")).values())[0]
    review_pages = Paginator(reviews, 5)
    page_number = request.GET.get("page")
    page_obj = review_pages.get_page(page_number)
     
    return render(request, "store/products/single.html", {"product": product, "reviews": reviews, "review_pages":page_obj,  "avg_rate": avg_rate, "no_review": len(reviews)})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(
        request,
        "store/products/category.html",
        {"category": category, "products": products},
    )

web/cbay/store/templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}

{% block name %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %} 
{% endblock %}
{% endblock %}

{% block content %}



<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{ category.name   }}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                
              </p>
              <div class="d-flex justify-content-end align-items-left">
                <small class="text-muted"> £{{ product.price  }} </small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>

</main>


{% endblock %}

web/cbay/store/templates/store/products/single.html
{% extends "../base.html" %}
{% load static %}


{% block name %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Products{% endif %}
{% endblock %}
{% endblock %}

{% block content %}
<style type="text/css">
    .checked {
        color:
            #ffc700
    }
</style>
<div class="container">
    <main class="pt-5">
        <div>
            <h1 class="col-md-5 col-lg-5 order-md-first">{{ product.title }}</h1>
            <div class="row">
                <div class="col-md-4">
                    {% if avg_rate <= 1.0 %} <span name="star" class="fa fa-star checked"></span>
                        <span name="star" class="fa fa-star"></span>
                        <span name="star" class="fa fa-star"></span>
                        <span name="star" class="fa fa-star"></span>
                        <span name="star" class="fa fa-star"></span>
                        {% endif %}
                        {% if 1.0 < avg_rate and avg_rate <= 2.0 %} <span name="star" class="fa fa-star checked"></span>
                            <span name="star" class="fa fa-star checked"></span>
                            <span name="star" class="fa fa-star"></span>
                            <span name="star" class="fa fa-star"></span>
                            <span name="star" class="fa fa-star"></span>
                            {% endif %}
                            {% if 2.0 < avg_rate and avg_rate <= 3.0 %} <span name="star" class="fa fa-star checked">
                                </span>
                                <span name="star" class="fa fa-star checked"></span>
                                <span name="star" class="fa fa-star checked"></span>
                                <span name="star" class="fa fa-star"></span>
                                <span name="star" class="fa fa-star"></span>
                                {% endif %}
                                {% if 3 < avg_rate and avg_rate <= 4 %} <span name="star" class="fa fa-star checked">
                                    </span>
                                    <span name="star" class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star"></span>
                                    {% endif %}
                                    {% if 4 < avg_rate and avg_rate <= 5 %} <span name="star" class="fa fa-star checked">
                                        </span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <p>({{ no_review }} reviews)</p>
                </div>
            </div>
        </div>
        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image"
                    src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h3">{{ product.subtitle }}</h1>
                <p></p>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Unit price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                    <option value="">5</option>
                                    <option value="">6</option>
                                    <option value="">7</option>
                                    <option value="">8</option>
                                    <option value="">9</option>
                                </select>

                            </div>


                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm"
                                    id="add-button" value="{{product.id}}">Add to basket</button></div>
                        </div>
                    </div>
                </div>
                <p></p>
                <span class="lead">Uses</span>
                <p>{{ product.uses }}</p>


                <span class="lead">Dosage</span>
                <p>{{ product.dosage }}</p>


                <span class="lead">Side effects</span>
                <p>{{ product.side_effects }}</p>
            </div>
        </div>
        <hr>
        <h1 class="col-md-5 col-lg-5 order-md-first">Reviews</h1>
        <div class="container" style="max-width: 1000px">
            {% for review in review_pages %}
            <div class="row border-bottom">

                <div class="col-12 bg-light p-3 d-flex justify-content-between">


                    <div class="row">
                        <div class="col"><span>{{review.created}}</span></div>
                    </div>
                    <div class="col-sm-4 col-md-2" style="justify-content: right;">
                        {% if review.rate <= 1.0 %} <span name="star" class="fa fa-star checked"></span>
                            <span name="star" class="fa fa-star"></span>
                            <span name="star" class="fa fa-star"></span>
                            <span name="star" class="fa fa-star"></span>
                            <span name="star" class="fa fa-star"></span>
                            {% endif %}
                            {% if 1.0 < review.rate and review.rate <= 2.0 %} <span name="star"
                                class="fa fa-star checked"></span>
                                <span name="star" class="fa fa-star checked"></span>
                                <span name="star" class="fa fa-star"></span>
                                <span name="star" class="fa fa-star"></span>
                                <span name="star" class="fa fa-star"></span>
                                {% endif %}
                                {% if 2.0 < review.rate and review.rate <= 3.0 %} <span name="star"
                                    class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star checked"></span>
                                    <span name="star" class="fa fa-star"></span>
                                    <span name="star" class="fa fa-star"></span>
                                    {% endif %}
                                    {% if 3.0 < review.rate and review.rate <= 4.0 %} <span name="star"
                                        class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star checked"></span>
                                        <span name="star" class="fa fa-star"></span>
                                        {% endif %}
                                        {% if 4.0 < review.rate and review.rate <= 5.0 %} <span name="star"
                                            class="fa fa-star checked"></span>
                                            <span name="star" class="fa fa-star checked"></span>
                                            <span name="star" class="fa fa-star checked"></span>
                                            <span name="star" class="fa fa-star checked"></span>
                                            <span name="star" class="fa fa-star checked"></span>
                                            {% endif %}
                    </div>
                    <!-- <br> -->
                </div>
                <div class="row"><span>{{ review.comment }}</span></div>
            </div>
            {% endfor %}
            <div class="pagination"  style="justify-content: center;">
                <span class="step-links">

                    <div class="row">
                        <span class="current">
                            Page {{ review_pages.number }} of {{ review_pages.paginator.num_pages }}.
                        </span>
                    </div>
                    {% if review_pages.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    {% if review_pages.has_next %}   
                    <a href="?page={{ review_pages.next_page_number }}">next</a>
                    <a href="?page={{ review_pages.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            </div>
        </div>
    </main>

</div>




<script>
    // Update basket counter
    $(document).on("click", "#add-button", function (e) {
        e.preventDefault();

        $.ajax({
            type: "POST",
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: "post"
            },
            success: function (json) {
                document.getElementById("basket_qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) { }
        });
    })
</script>
{%endblock%}